### ISSUE TITLE
Error in restarting geolocator service in background

### ISSUE THREAD

**Issue by huynhphucloi** [Baseflow/flutter-geolocator#1178]
## 💬 Questions and Help

For questions or help we recommend checking:

i have use plugin in getting GPS data in background. i have tried disabling the Location service and turning it back on to check if it works. After disabling location services, the log message is as follows:

`E/FlutterGeolocator( 8931): Geolocator position updates stopped
D/FlutterGeolocator( 8931): Stopping location service.
D/FlutterGeolocator( 8931): Stop service in foreground.
E/FlutterGeolocator( 8931): Geolocator position updates started using Android foreground service
D/FlutterGeolocator( 8931): Start service in foreground mode.`

then i re-enable location service and try to restart geolocator's location service but throw error:

`E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at com.baseflow.geolocator.GeolocatorLocationService.enableBackgroundMode(GeolocatorLocationService.java:148)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at com.baseflow.geolocator.StreamHandlerImpl.onListen(StreamHandlerImpl.java:130)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at android.os.Handler.handleCallback(Handler.java:942)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at android.os.Looper.loopOnce(Looper.java:201)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at android.os.Looper.loop(Looper.java:288)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/EventChannel#flutter.baseflow.com/geolocator_updates_android( 8931): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

════════ Exception caught by services library ══════════════════════════════════
The following PlatformException was thrown while activating platform stream on channel flutter.baseflow.com/geolocator_updates_android:
PlatformException(error, Service.startForeground() not allowed due to mAllowStartForeground false: service com.example.location_shop/com.baseflow.geolocator.GeolocatorLocationService, null, null)

When the exception was thrown, this was the stack
#0      StandardMethodCodec.decodeEnvelope
package:flutter/…/services/message_codecs.dart:653
#1      MethodChannel._invokeMethod
package:flutter/…/services/platform_channel.dart:296
<asynchronous suspension>
#2      EventChannel.receiveBroadcastStream.<anonymous closure>
package:flutter/…/services/platform_channel.dart:637
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════`

Look forward to the help. thank

**Comment by JeroenWeener** [comment]
Hi @huynhphucloi, thank you for opening this issue!

To effectively tackle this issue, we require some additional information. Could you provide us with a minimal code example that showcases your use case? Also, am I correct in assuming that this issue is only relevant on Android devices?
