### ISSUE TITLE
IncompatibleClassChangeError After upgrading from Flutter 3.3 to 3.7

### ISSUE THREAD

**Issue by maichongju** [Baseflow/flutter-geolocator#1207]
I just upgraded my flutter from 3.3 to 3.7. Then all the sudden, the program crashed at the start with the following message.

```
E/AndroidRuntime( 8044): FATAL EXCEPTION: main
E/AndroidRuntime( 8044): Process: com.example.map, PID: 8044
E/AndroidRuntime( 8044): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~SxuGh26HWKQ1rIvCYXX3qA==/com.example.map-0DBQ_0B_UFjIyX_goSaXhw==/base.apk)
E/AndroidRuntime( 8044): 	at com.lyokone.location.FlutterLocation.createLocationCallback(FlutterLocation.java:219)
E/AndroidRuntime( 8044): 	at com.lyokone.location.FlutterLocation.changeSettings(FlutterLocation.java:197)
E/AndroidRuntime( 8044): 	at com.lyokone.location.MethodCallHandlerImpl.onChangeSettings(MethodCallHandlerImpl.java:106)
E/AndroidRuntime( 8044): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/AndroidRuntime( 8044): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/AndroidRuntime( 8044): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime( 8044): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/AndroidRuntime( 8044): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime( 8044): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 8044): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 8044): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime( 8044): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime( 8044): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime( 8044): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 8044): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime( 8044): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
I/Process ( 8044): Sending signal. PID: 8044 SIG: 9
Lost connection to device.
```

I have tried so many things including downgrading the flutter back to 3.3. But no luck. If anyone can help me find the root cause for this it will be great.  

Package used

```
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.4
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  sqflite: ^2.0.3+1
  path_provider: ^2.0.11
  crypto: ^3.0.2
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  cloud_firestore: ^4.3.1
  freezed: ^2.1.0+1
  firebase_auth: ^4.2.5
  flutter_speed_dial: ^6.0.0
  datetime_picker_formfield: ^2.0.1
  google_maps_place_picker_mb: ^2.0.0-mb.22
  geolocator: ^9.0.2
  google_maps_webservice: ^0.0.19
  tuple: ^2.0.0
  flutter_chat_ui: ^1.6.4
  go_router: ^5.0.1
```

**Comment by christocracy** [comment]
When you upgraded Flutter, `pub get` was run, causing your app to fetch the latest *point release*.

see [this recent pull request](https://github.com/Baseflow/flutter-geolocator/pull/1202#issuecomment-1406859865)

**Comment by idreesVenD** [comment]
I didn't update flutter and still getting this error :(

**Comment by maichongju** [comment]
@idreesVenD So in short, there is nothing wrong with geolocator. It is because of geolocator_android bumped google service version up which creates problem. 

The solution from below might help :)

https://github.com/transistorsoft/flutter_background_geolocation/issues/933#issuecomment-1407797107
