### ISSUE TITLE
[Bug]: java.lang.RuntimeException when access getPositionStream

### ISSUE THREAD

**Issue by zgramming** [Baseflow/flutter-geolocator#1286]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Listen position using function `getPositionStream`

### Expected results

Will listen position

### Actual results

not listen and showing error message.

```console
E/FlutterGeolocator(11293): Geolocator position updates stopped
E/FlutterGeolocator(11293): There is still another flutter engine connected, not stopping location service
E/FlutterGeolocator(11293): Geolocator position updates started
D/LocationManager(11293): [LocationManager] requestLocationUpdates(),
D/LocationManager(11293): java.lang.RuntimeException
D/LocationManager(11293): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1013)
D/LocationManager(11293): 	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:595)
D/LocationManager(11293): 	at com.baseflow.geolocator.location.LocationManagerClient.startPositionUpdates(LocationManagerClient.java:198)
D/LocationManager(11293): 	at com.baseflow.geolocator.location.GeolocationManager.startPositionUpdates(GeolocationManager.java:55)
D/LocationManager(11293): 	at com.baseflow.geolocator.StreamHandlerImpl.onListen(StreamHandlerImpl.java:137)
D/LocationManager(11293): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:218)
D/LocationManager(11293): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:197)
D/LocationManager(11293): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
D/LocationManager(11293): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
D/LocationManager(11293): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
D/LocationManager(11293): 	at android.os.Handler.handleCallback(Handler.java:874)
D/LocationManager(11293): 	at android.os.Handler.dispatchMessage(Handler.java:100)
D/LocationManager(11293): 	at android.os.Looper.loop(Looper.java:198)
D/LocationManager(11293): 	at android.app.ActivityThread.main(ActivityThread.java:6729)
D/LocationManager(11293): 	at java.lang.reflect.Method.invoke(Native Method)
D/LocationManager(11293): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
D/LocationManager(11293): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
```

### Code sample

<details><summary>Code sample</summary>

```dart
void listenPosition() {
    try {
      LocationSettings locationSettings = const LocationSettings();
      if (defaultTargetPlatform == TargetPlatform.android) {
        locationSettings = AndroidSettings(
          accuracy: LocationAccuracy.high,
          // distanceFilter: 100,
          forceLocationManager: true,
          // intervalDuration: const Duration(seconds: 10),
          //(Optional) Set foreground notification config to keep the app alive
          //when going to the background
          // foregroundNotificationConfig: const ForegroundNotificationConfig(
          //   notificationText: "We're fetching your location in the background",
          //   notificationTitle: "Running in Background",
          //   enableWakeLock: true,
          // ),
        );
      } else if (defaultTargetPlatform == TargetPlatform.iOS ||
          defaultTargetPlatform == TargetPlatform.macOS) {
        locationSettings = AppleSettings(
          accuracy: LocationAccuracy.high,
          activityType: ActivityType.fitness,
          distanceFilter: 100,
        );
      } else {
        locationSettings = const LocationSettings(
          accuracy: LocationAccuracy.high,
          distanceFilter: 100,
        );
      }

      final stream =
          Geolocator.getPositionStream(locationSettings: locationSettings);

      stream.listen((position) {
        log("Current Position: $position");
      });
    } catch (e) {
      log(e.toString());
    }
  }

  @override
  void initState() {
    super.initState();

    listenPosition();
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
PS C:\project_flutter\pik\idf-project\idf-app-v2> flutter doctor -v
[√] Flutter (Channel stable, 3.10.4, on Microsoft Windows [Version 10.0.22621.1848], locale en-ID)
    • Flutter version 3.10.4 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 682aa387cf (5 weeks ago), 2023-06-05 18:04:56 -0500
    • Engine revision 2a3401c9bb
    • Dart version 3.0.3
    • DevTools version 2.23.1

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at C:\Users\zeffr\AppData\Local\Android\sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)

[√] VS Code (version 1.80.0)
    • VS Code at C:\Users\zeffr\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.68.0

[√] Connected device (5 available)
    • SH C02 (mobile)              • VGOLHMA031701975 • android-arm64  • Android 9 (API 28)
    • sdk gphone64 x86 64 (mobile) • emulator-5554    • android-x64    • Android 13 (API 33) (emulator)
    • Windows (desktop)            • windows          • windows-x64    • Microsoft Windows [Version 10.0.22621.1848]
    • Chrome (web)                 • chrome           • web-javascript • Google Chrome 114.0.5735.199
    • Edge (web)                   • edge             • web-javascript • Microsoft Edge 114.0.1823.67

[√] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by JeroenWeener** [comment]
Hi @zgramming, thanks for filing a bug report.

I took your code and created a minimal reproducible code sample. You can find the `main.dart` here: https://gist.github.com/JeroenWeener/84321a0a836ccc720b5853156648d698.

When I run the code on an emulator running Android 13, I do not encounter the issue.

I'd be happy to help if you can provide me with additional info.
