### ISSUE TITLE
[Bug]: Conflict of "com.google.android.gms:play-services-location:20.0.0" and geolocator_android 4.2.1+

### ISSUE THREAD

**Issue by jb3rndt** [Baseflow/flutter-geolocator#1300]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Add
```
configurations.all {
    resolutionStrategy {
        force "com.google.android.gms:play-services-location:20.0.0"
    }
}
```

to the `build.gradle` file. (https://github.com/Baseflow/flutter-geolocator/issues/1189#issuecomment-1377324199)
This effectively fixes the following error for me, when using the mapbox sdk v6 on android:
<details>
  <summary>Logs:</summary>

```
W/System.err(10842): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~Wy1lpeVgHLReg64X3N1P6g==/twentyfoureight.app-fc4G-YwBwMG_t1dU9_89CQ==/base.apk)
W/System.err(10842): 	at com.mapbox.android.core.location.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:58)
W/System.err(10842): 	at com.mapbox.android.core.location.GoogleLocationEngineImpl.requestLocationUpdates(GoogleLocationEngineImpl.java:26)
W/System.err(10842): 	at com.mapbox.android.core.location.LocationEngineProxy.requestLocationUpdates(LocationEngineProxy.java:34)
W/System.err(10842): 	at com.mapbox.mapboxsdk.location.LocationComponent.onLocationLayerStart(LocationComponent.java:1439)
W/System.err(10842): 	at com.mapbox.mapboxsdk.location.LocationComponent.enableLocationComponent(LocationComponent.java:1568)
W/System.err(10842): 	at com.mapbox.mapboxsdk.location.LocationComponent.setLocationComponentEnabled(LocationComponent.java:551)
W/System.err(10842): 	at com.mapbox.mapboxgl.MapboxMapController.enableLocationComponent(MapboxMapController.java:280)
W/System.err(10842): 	at com.mapbox.mapboxgl.MapboxMapController.updateMyLocationEnabled(MapboxMapController.java:1809)
W/System.err(10842): 	at com.mapbox.mapboxgl.MapboxMapController.access$100(MapboxMapController.java:98)
W/System.err(10842): 	at com.mapbox.mapboxgl.MapboxMapController$1.onStyleLoaded(MapboxMapController.java:147)
W/System.err(10842): 	at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:963)
W/System.err(10842): 	at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:225)
W/System.err(10842): 	at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1383)
W/System.err(10842): 	at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:198)
W/System.err(10842): 	at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1166)
W/System.err(10842): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(10842): 	at android.os.MessageQueue.next(MessageQueue.java:335)
W/System.err(10842): 	at android.os.Looper.loopOnce(Looper.java:162)
W/System.err(10842): 	at android.os.Looper.loop(Looper.java:294)
W/System.err(10842): 	at android.app.ActivityThread.main(ActivityThread.java:8176)
W/System.err(10842): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(10842): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
W/System.err(10842): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```
</details>

Unfortunately, "com.google.android.gms:play-services-location:21.0.1" (https://github.com/Baseflow/flutter-geolocator/issues/1214#issuecomment-1463379573) gives the same error while 20.0.0 does not.

The problem with 20.0.0 is that it does not work in combination with geolocator_android 4.2.1+ -> The following error gets thrown:

<details>
  <summary>Logs:</summary>

```
[        ] /Users/jberndt/.pub-cache/hosted/pub.dev/geolocator_android-4.2.1/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:91: error: cannot find
symbol
[   +1 ms]     LocationRequest.Builder builder = new LocationRequest.Builder(0);
[        ]                    ^
[        ]   symbol:   class Builder
[        ]   location: class LocationRequest
[        ] /Users/jberndt/.pub-cache/hosted/pub.dev/geolocator_android-4.2.1/android/src/main/java/com/baseflow/geolocator/location/FusedLocationClient.java:91: error: cannot find
symbol
[        ]     LocationRequest.Builder builder = new LocationRequest.Builder(0);
[        ]                                                          ^
[        ]   symbol:   class Builder
[        ]   location: class LocationRequest
[        ] 2 errors
[        ] FAILURE: Build failed with an exception.
[        ] * What went wrong:
[        ] Execution failed for task ':geolocator_android:compileDebugJavaWithJavac'.
[        ] > Compilation failed; see the compiler error output for details.
[        ] * Try:
[        ] > Run with --debug option to get more log output.
[        ] > Run with --scan to get full insights.
```
</details>

I'm still trying to narrow the problem down, but any help is much appreciated :)

### Expected results

App compiles

### Actual results

App doesnt compile

### Code sample

<details><summary>Code sample</summary>

```dart
Still working on that
```

</details>

### Version

9.0.2

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.4.1 22F770820d darwin-arm64, locale de-DE)
    • Flutter version 3.10.6 on channel stable at /Users/jberndt/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (4 weeks ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/jberndt/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (2 available)
    • sdk gphone64 arm64 (mobile) • emulator-5554 • android-arm64 • Android 14 (API 34) (emulator)
    • macOS (desktop)             • macos         • darwin-arm64  • macOS 13.4.1 22F770820d darwin-arm64

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by jb3rndt** [comment]
I guess `https://github.com/flutter-mapbox-gl/maps` is just too outdated at this point. Im not sure if it is any worth looking deeper into it...?
