### ISSUE TITLE
[Bug]: Package doesn't work in Flutter's release apk, while testing on other devices, debug apk works with no flaws

### ISSUE THREAD

**Issue by venkylm10** [Baseflow/flutter-geolocator#1389]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

Run a Flutter app which uses geolocator to get current location on a android device by installing its app-release.apk file. Make sure app has loading effect in-between loading current location.

### Expected results

Package should get location data and loading should stop.

### Actual results

Package doesn't work and won't get location data and app keeps on loading.

### Code sample

<details><summary>Code sample</summary>

```dart
  var loading = true;
  Future<bool> handleLocationPermission() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      showSnackBar(
          message:
              'Location services are needed to get your zipcode and country dial code',
          duration: 3);
      setState(() {
        loading = false;
      });
      return false;
    }
    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        showSnackBar(
            message:
                'Location services are needed to get your zipcode and country dial code');
        setState(() {
          loading = false;
        });
        return false;
      }
    }
    if (permission == LocationPermission.deniedForever) {
      showSnackBar(
          message:
              'Location services are needed to get your zipcode and country dial code');
      setState(() {
        loading = false;
      });
      return false;
    }
    return true;
  }

  Future<void> getLocationInfo() async {
    Position position = await Geolocator.getCurrentPosition();
    List<Placemark> placemarks =
        await placemarkFromCoordinates(position.latitude, position.longitude);
    Placemark placemark = placemarks.first;
    String zipcode = placemark.postalCode ?? "";
    zipcodeController.text = zipcode;
    this.zipcode = zipcode;
    city = placemark.locality ?? "";
    country = placemark.country ?? "";
    if (placemark.isoCountryCode != null) {
      countryDialCode =
          CountryDialCode.fromCountryCode(placemark.isoCountryCode!).dialCode;
    }
  }

  void initialise() async {
    await handleLocationPermission();
    await getLocationInfo();
    if (isMounted) {
      setState(() {
        loading = false;
        mobileController.text =
            ref.read(authProvider).currentUser!.phoneNumber ?? "";
      });
    }
  }

  @override
  void initState() {
    initialise();
    zipcodeController = TextEditingController();
    mobileController = TextEditingController();
    super.initState();
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

10.1.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.16.2, on Ubuntu 22.04.3 LTS 6.2.0-37-generic, locale en_US.UTF-8)
    • Flutter version 3.16.2 on channel stable at /home/venky/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 9e1c857886 (2 days ago), 2023-11-30 11:51:18 -0600
    • Engine revision cf7a9d0800
    • Dart version 3.2.2
    • DevTools version 2.28.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /home/venky/Android/Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /usr/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+9-Ubuntu-122.04)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] VS Code (version unknown)
    • VS Code at /snap/code/current
    • Flutter extension version 3.76.0
    ✗ Unable to determine VS Code version.

[✓] Connected device (3 available)
    • moto g71 5G (mobile) • ZD222758PJ • android-arm64  • Android 12 (API 31)
    • Linux (desktop)      • linux      • linux-x64      • Ubuntu 22.04.3 LTS 6.2.0-37-generic
    • Chrome (web)         • chrome     • web-javascript • Google Chrome 119.0.6045.199

[✓] Network resources
    • All expected network resources are available.

! Doctor found issues in 1 category.
```

</details>

**Comment by ArielFarias** [comment]
We are having the same problem here. Just released the app today, and we have now many crashs on our report system. The error that is being thrown is this:

```dart
Fatal Exception: java.lang.IncompatibleClassChangeError: Found interface a8.b, but class was expected (declaration of 'a8.b' appears in base.apk)
       at com.lyokone.location.FlutterLocation.setActivity(FlutterLocation.java:32)
       at com.lyokone.location.FlutterLocationService.setActivity(FlutterLocationService.java:6)
       at com.lyokone.location.LocationPlugin.dispose(LocationPlugin.java:51)
       at com.lyokone.location.LocationPlugin.detachActivity(LocationPlugin.java)
       at com.lyokone.location.LocationPlugin.onDetachedFromActivity(LocationPlugin.java)
       at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.detachFromActivity(FlutterEngineConnectionRegistry.java:33)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:58)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:18)
       at android.app.Activity.performDestroy(Activity.java:8571)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1364)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5937)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5995)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8663)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
``` 
Doctor output:

```shell
[√] Flutter (Channel stable, 3.7.7, on Microsoft Windows [versÆo 10.0.19045.3693], locale pt-BR)
[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 4.0)
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

**Comment by mvanbeusekom** [comment]
Hi @venkylm10,

Thank you for supplying the contents of the `AndroidManifest.xml` file. Can you please confirm the path of the `AndroidManifest.xml` file? 

When you only add the permissions to the `AndroidManifest.xml` file that is located on the path `android/app/src/debug` or `android/app/src/profile` the configuration is not included in the final release build. So please make sure the configuration is added to the `AndroidManifest.xml` located in the `android/app/src/main` folder.
