### ISSUE TITLE
[Bug]: App crashes when calling getCurrentPosition()

### ISSUE THREAD

**Issue by muhammad67uzair** [Baseflow/flutter-geolocator#1515]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. add the geolocator plugin
2. add the access.coarse.location permission in androidmanifest.xml
3. call geolocator.getCurrentPosition();

### Expected results

the coarse location/position of the user should be returned.

### Actual results

App crashes when calling geolocator.getCurrentPosition();
i have added the android.permission.ACCESS_COARSE_LOCATION in my AndroidManifest.xml file, but when the app requests the user's current position the app crashes with the following exception:

D/AndroidRuntime(11738): Shutting down VM
E/AndroidRuntime(11738): FATAL EXCEPTION: main
E/AndroidRuntime(11738): Process: com.lu.ufcw1167, PID: 11738
E/AndroidRuntime(11738): java.lang.SecurityException: Neither user 10373 nor current process has android.permission.ACCESS_FINE_LOCATION.

although im not even requesting user's fine location.

I even tried specifying a specific geolocator version like 11.0.0 and previous ones but to no avail. 

complete error log:

E/AndroidRuntime(11738): java.lang.SecurityException: Neither user 10373 nor current process has android.permission.ACCESS_FINE_LOCATION.
E/AndroidRuntime(11738): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/AndroidRuntime(11738): 	at android.os.Parcel.createException(Parcel.java:3041)
E/AndroidRuntime(11738): 	at android.os.Parcel.readException(Parcel.java:3024)
E/AndroidRuntime(11738): 	at android.os.Parcel.readException(Parcel.java:2966)
E/AndroidRuntime(11738): 	at android.location.ILocationManager$Stub$Proxy.registerGnssNmeaCallback(ILocationManager.java:1625)
E/AndroidRuntime(11738): 	at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:3127)
E/AndroidRuntime(11738): 	at android.location.LocationManager$GnssNmeaTransportManager.registerTransport(LocationManager.java:3117)
E/AndroidRuntime(11738): 	at com.android.internal.listeners.ListenerTransportManager.addListener(ListenerTransportManager.java:70)
E/AndroidRuntime(11738): 	at android.location.LocationManager.addNmeaListener(LocationManager.java:2629)
E/AndroidRuntime(11738): 	at android.location.LocationManager.addNmeaListener(LocationManager.java:2610)
E/AndroidRuntime(11738): 	at com.baseflow.geolocator.location.NmeaClient.start(NmeaClient.java:76)
E/AndroidRuntime(11738): 	at com.baseflow.geolocator.location.FusedLocationClient.requestPositionUpdates(FusedLocationClient.java:157)
E/AndroidRuntime(11738): 	at com.baseflow.geolocator.location.FusedLocationClient.lambda$startPositionUpdates$2$com-baseflow-geolocator-location-FusedLocationClient(FusedLocationClient.java:240)
E/AndroidRuntime(11738): 	at com.baseflow.geolocator.location.FusedLocationClient$$ExternalSyntheticLambda3.onSuccess(Unknown Source:4)
E/AndroidRuntime(11738): 	at com.google.android.gms.tasks.zzm.run(com.google.android.gms:play-services-tasks@@18.1.0:1)
E/AndroidRuntime(11738): 	at android.os.Handler.handleCallback(Handler.java:958)
E/AndroidRuntime(11738): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(11738): 	at android.os.Looper.loopOnce(Looper.java:224)
E/AndroidRuntime(11738): 	at android.os.Looper.loop(Looper.java:318)
E/AndroidRuntime(11738): 	at android.app.ActivityThread.main(ActivityThread.java:8720)
E/AndroidRuntime(11738): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11738): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
E/AndroidRuntime(11738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
E/AndroidRuntime(11738): Caused by: android.os.RemoteException: Remote stack trace:
E/AndroidRuntime(11738): 	at android.app.ContextImpl.enforce(ContextImpl.java:2343)
E/AndroidRuntime(11738): 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:2371)
E/AndroidRuntime(11738): 	at com.android.server.location.gnss.GnssManagerService.registerGnssNmeaCallback(GnssManagerService.java:206)
E/AndroidRuntime(11738): 	at com.android.server.location.LocationManagerService.registerGnssNmeaCallback(LocationManagerService.java:1151)
E/AndroidRuntime(11738): 	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:809)
E/AndroidRuntime(11738): 
2
W/VideoCapabilities(11738): Unsupported mime image/vnd.android.heic
W/ScoutUtils(11738): Failed to mkdir /data/miuilog/stability/memleak/heapdump/
I/Process (11738): Process is going to kill itself!
I/Process (11738): java.lang.Exception
I/Process (11738): 	at android.os.Process.killProcess(Process.java:1356)
I/Process (11738): 	at com.android.internal.os.RuntimeInit$KillApplicationHandler.uncaughtException(RuntimeInit.java:174)
I/Process (11738): 	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-stable-636712333:27)
I/Process (11738): 	at com.datadog.android.error.internal.DatadogExceptionHandler.uncaughtException(DatadogExceptionHandler.kt:98)
I/Process (11738): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
I/Process (11738): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
I/Process (11738): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
I/Process (11738): Sending signal. PID: 11738 SIG: 9
Lost connection to device.

### Code sample

<details><summary>Code sample</summary>

```dart
  Future<void> _updateUserLocation() async {
    LocationPermission permission = await Geolocator.checkPermission();
    if (<LocationPermission>[LocationPermission.denied, LocationPermission.deniedForever]
        .contains(permission)) {
      permission = await Geolocator.requestPermission();
      if (<LocationPermission>[
        LocationPermission.denied,
        LocationPermission.deniedForever,
      ].contains(permission)) {
        throw Exception(
          'Location permissions are permanently denied, we cannot request permissions.',
        );
      }
    }
    permission = await Geolocator.checkPermission();
    if (<LocationPermission>[LocationPermission.whileInUse, LocationPermission.always]
        .contains(permission)) {
      final Position position = await Geolocator.getCurrentPosition(
        desiredAccuracy: LocationAccuracy.high,
      );
  }
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

12.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.9, on macOS 14.4.1 23E224 darwin-arm64, locale
    en-AU)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (3 available)
    ! Error: Browsing on the local area network for Avialdo’s iPhone Xr. Ensure
      the device is unlocked and attached with a cable or associated with the
      same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
    ! Error: Browsing on the local area network for Avialdo Solutions’s iPhone
      12 mini. Ensure the device is unlocked and attached with a cable or
      associated with the same local area network as this Mac.
      The device must be opted into Developer Mode to connect wirelessly. (code
      -27)
[✓] Network resources

• No issues found!
```

</details>

**Comment by mvanbeusekom** [comment]
Try specifying a lower accuracy. 

Acquiring a location with accuracy of `high` and up require the fine permission.

**Comment by muhammad67uzair** [comment]
> Try specifying a lower accuracy.
> 
> Acquiring a location with accuracy of `high` and up require the fine permission.

@mvanbeusekom i tried specifying the low accuracy but it still didn't work, i even added the ACCESS_FINE_LOCATION permission in my manifest file, with both low and high accuracies but still got the same error.

also it used to work before with high accuracy without the need to add the ACCESS_FINE_LOCATION permission, this happened after the version 12.0.0 and like @RokuIL said, reverting back to version 11.0.0 or even a previous version doesn't help.

**Comment by muhammad67uzair** [comment]
> @muhammad67uzair
> 
> After upgrading from 11.0.0 (worked) to 12.0.0 (crashed), reverting back to 11.0.0 wasn't enough. I needed to restore the values in my pubspec.lock to:
> 
> geolocator: dependency: "direct main" description: name: geolocator sha256: "694ec58afe97787b5b72b8a0ab78c1a9244811c3c10e72c4362ef3c0ceb005cd" url: "https://pub.dev" source: hosted version: "11.0.0" geolocator_android: dependency: transitive description: name: geolocator_android sha256: f15d1536cd01b1399578f1da1eb5d566e7a718db6a3648f2c24d2e2f859f0692 url: "https://pub.dev" source: hosted version: "4.5.4" geolocator_apple: dependency: transitive description: name: geolocator_apple sha256: bc2aca02423ad429cb0556121f56e60360a2b7d694c8570301d06ea0c00732fd url: "https://pub.dev" source: hosted version: "2.3.7" geolocator_platform_interface: dependency: transitive description: name: geolocator_platform_interface sha256: "009a21c4bc2761e58dccf07c24f219adaebe0ff707abdfd40b0a763d4003fab9" url: "https://pub.dev" source: hosted version: "4.2.2" geolocator_web: dependency: transitive description: name: geolocator_web sha256: "49d8f846ebeb5e2b6641fe477a7e97e5dd73f03cbfef3fd5c42177b7300fb0ed" url: "https://pub.dev" source: hosted version: "3.0.0" geolocator_windows: dependency: transitive description: name: geolocator_windows sha256: "53da08937d07c24b0d9952eb57a3b474e29aae2abf9dd717f7e1230995f13f0e" url: "https://pub.dev" source: hosted version: "0.2.3"

@RokuIL thanks, that worked!

**Comment by corepuncher** [comment]
Both .medium and .high have always worked for me using:

  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
   
However, geolocator no longer works for my Windows app.  It put my location in southern Virginia.  And it's not my computer, because I build the app and sent it to someone in another state, and they too show Virginia as they location.  Any thoughts on this would be appreciated. Am I the only one with this issue so far?

**Comment by muhammad67uzair** [comment]
based on @RokuIL's comment, it seems to be an issue in the platform specific geolocator packages that geolocator itself depends upon.

instead of manually modifying the pubspec.lock file, we could just directly specify the versions of the packages that geolocator itself depends upon in our pubspec.yaml file like this:

dependencies:
  geolocator: 11.0.0
  geolocator_android: 4.5.4
  geolocator_apple: 2.3.7
  
  or like 
  
  dependencies:
    geolocator: 11.0.0
  
  dependency_overrides:
    geolocator_android: 4.5.4
    geolocator_apple: 2.3.7

**Comment by rminkler1** [comment]
I just tested these dependencies:
  geolocator: ^12.0.0
  geolocator_android: 4.5.4

It works fine. Clearly it is an issue with the newer geolocator_android release.

I've been following a tutorial as I learn Flutter, updated Flutter. Could not figure out why this app kept crashing. Saw it is a dependency issue. I'm glad it's not just me doing something stupid.

**Comment by cedvdb** [comment]
Same with fine location added:

```
  <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
  <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
```

Adding the override fixes the issue

```
# Fix for https://github.com/Baseflow/flutter-geolocator/issues/1515
dependency_overrides:
  geolocator_android: 4.5.4
```

**Comment by KirillArtemenko** [comment]
I confirm it, geolocator 12.0.0 works well with geolocator_android 4.5.5. I'll probably stay with this configuration.
Interesting, on Pixel with latest Android version 4.6.0 works ok, but on Xiaomi crashes with 50% rate.

Obviously, this commit make this issue:
https://github.com/Baseflow/flutter-geolocator/commit/6b34bebdfbfc5a7d595652cd5a470da4dbc1a129

**Comment by agboolaidris** [comment]
This work for me

**Comment by gojaca** [comment]
I received the crash notice on Crashlytics.

I was able to reproduce by disabling the "Precise Location" setting under Location Permissions for the app (Android OS). After launching the app, it simply crashes.

To solve I used the suggested fix by adding into pubspec.yaml:

dependency_overrides:
  geolocator_android: 4.5.4

**Comment by iamalok12** [comment]
Getting this error 

`E/AndroidRuntime(15144): FATAL EXCEPTION: pool-2-thread-7
E/AndroidRuntime(15144): Process: in.clovertech.bumblebee.columbus, PID: 15144
E/AndroidRuntime(15144): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~-vBZnqHBVDN2NBtEj8HeGA==/in.clovertech.bumblebee.columbus-7XfLGqZRS1uqOPS--Zjvvw==/base.apk)
E/AndroidRuntime(15144): 	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.removeLocationUpdates(Unknown Source:50)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.location.TSLocationManager.d(Unknown Source:40)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:83)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(Unknown Source:2)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw(Unknown Source:0)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime(15144): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(15144): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(15144): 	at java.lang.Thread.run(Thread.java:1012)
I/Process (15144): Sending signal. PID: 15144 SIG: 9
Lost connection to device.`




my pubspec.yaml

`environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  url_launcher: ^6.0.10
  http: ^0.13.3
  qr_flutter: ^4.0.0
  protobuf: ^2.0.0
  pin_code_fields: ^7.3.0
  fluttertoast: ^8.0.8
  future_progress_dialog: ^0.2.0
  provider: ^6.0.0
  package_info: ^2.0.2
  device_info: ^2.0.2
  version: ^2.0.0
  get: ^4.3.6
  screenshot: ^1.2.3
  share: ^2.0.4
  path_provider: ^2.0.2
  expansion_tile_card: ^2.0.0
  image_picker: ^0.8.4+1
  qr_code_scanner: ^0.5.2
  audioplayers: ^0.20.1
  path: ^1.7.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_secure_storage: ^4.2.1
  uuid: ^3.0.4
  flutter_background_geolocation: ^4.5.0
  internet_connection_checker: ^0.0.1+3
  connectivity_plus: ^2.3.6
  flutter_map: ^2.2.0
  amplitude_flutter: ^3.10.0
  event_bus: ^2.0.0
  flutter_jailbreak_detection: ^1.8.0
  rive: ^0.9.1

`

android build.gradle

`buildscript {
    ext.kotlin_version = '1.5.10'

    ext {
        compileSdkVersion   = 33                // or higher
        targetSdkVersion    = 33                // or higher
        appCompatVersion    = "1.1.0"           // or higher
        playServicesLocationVersion = "19.0.1"
    }
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven {
            url "${project(':flutter_background_geolocation').projectDir}/libs"
        }
        maven {
            // [required] background_fetch
            url "${project(':background_fetch').projectDir}/libs"
        }
        maven { url "https://jitpack.io" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

`


app level build.gradle

`def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

Project background_geolocation = project(':flutter_background_geolocation')
apply from: "${background_geolocation.projectDir}/background_geolocation.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion rootProject.ext.compileSdkVersion

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        minSdkVersion 20
        targetSdkVersion 33
        compileSdkVersion = 31
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        multiDexEnabled true
        manifestPlaceholders = [
                FLUTTER_BG_LICENSE_KEY: keystoreProperties['backgroundGeoLicense'],
        ]
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile keystoreProperties['storeFile'] ? file(keystoreProperties['storeFile']) : null
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.release
            shrinkResources false
            proguardFiles "${background_geolocation.projectDir}/proguard-rules.pro"
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
`

**Comment by iamalok12** [comment]
Im getting this error while running the app.

```
E/AndroidRuntime(15144): FATAL EXCEPTION: pool-2-thread-7
E/AndroidRuntime(15144): Process: in.clovertech.bumblebee.columbus, PID: 15144
E/AndroidRuntime(15144): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~-vBZnqHBVDN2NBtEj8HeGA==/in.clovertech.bumblebee.columbus-7XfLGqZRS1uqOPS--Zjvvw==/base.apk)
E/AndroidRuntime(15144): 	at com.transistorsoft.xms.g.location.FusedLocationProviderClient.removeLocationUpdates(Unknown Source:50)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.location.TSLocationManager.d(Unknown Source:40)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stopUpdatingLocation(Unknown Source:0)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.location.TSLocationManager.stop(Unknown Source:0)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.service.TrackingService.stop(Unknown Source:83)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.c(Unknown Source:2)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation.$r8$lambda$oSDeWXxQl1jmikdjYQwff60damw(Unknown Source:0)
E/AndroidRuntime(15144): 	at com.transistorsoft.locationmanager.adapter.BackgroundGeolocation$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime(15144): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(15144): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(15144): 	at java.lang.Thread.run(Thread.java:1012)
I/Process (15144): Sending signal. PID: 15144 SIG: 9
Lost connection to device.
```

**Comment by ShohruhSharipov1106** [comment]
I changed with location plugin and everything worked fine)

**Comment by mvanbeusekom** [comment]
I have just published version 4.6.1 of the geolocator_android package to pub.dev, to update please run flutter pub upgrade geolocator_android.
