### ISSUE TITLE
[Bug]: deprecated plugin warnings during build and "LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 0.)" error

### ISSUE THREAD

**Issue by ohalukkarakaya** [Baseflow/flutter-geolocator#1546]
### Please check the following before submitting a new issue.

- [X] I have searched the [existing issues](https://github.com/baseflow/flutter-geolocator/issues).
- [X] I have carefully [read the documentation](https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator/README.md) and verified I have added the required platform specific configuration.

### Please select affected platform(s)

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] macOS
- [ ] Web
- [ ] Windows

### Steps to reproduce

1. These warnings printed out to console while building app: 
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:40:31: warning: 'authorizationStatus' is deprecated: first deprecated in macOS 11.0 [-Wdeprecated-declarations]
    return [CLLocationManager authorizationStatus];
                              ^~~~~~~~~~~~~~~~~~~
                              authorizationStatus
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
+ (CLAuthorizationStatus)authorizationStatus API_DEPRECATED_WITH_REPLACEMENT("-authorizationStatus", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:47:65: warning: 'authorizationStatus' is deprecated: first deprecated in macOS 11.0 [-Wdeprecated-declarations]
  CLAuthorizationStatus authorizationStatus = CLLocationManager.authorizationStatus;
                                                                ^~~~~~~~~~~~~~~~~~~
                                                                authorizationStatus
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
+ (CLAuthorizationStatus)authorizationStatus API_DEPRECATED_WITH_REPLACEMENT("-authorizationStatus", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:47:65: warning: 'authorizationStatus' is deprecated: first deprecated in macOS 11.0 [-Wdeprecated-declarations]
  CLAuthorizationStatus authorizationStatus = CLLocationManager.authorizationStatus;
                                                                ^~~~~~~~~~~~~~~~~~~
                                                                authorizationStatus
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
+ (CLAuthorizationStatus)authorizationStatus API_DEPRECATED_WITH_REPLACEMENT("-authorizationStatus", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:107:1: warning: implementing deprecated method [-Wdeprecated-implementations]
- (void) locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status {
^
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status API_DEPRECATED_WITH_REPLACEMENT("-locationManagerDidChangeAuthorization:", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
4 warnings generated.
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/LocationServiceStreamHandler.m:36:1: warning: implementing deprecated method [-Wdeprecated-implementations]
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status{
^
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/LocationServiceStreamHandler.m:9:
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status API_DEPRECATED_WITH_REPLACEMENT("-locationManagerDidChangeAuthorization:", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^

2. when i used plugin to get geo location of the user, it never return location and printed this error to console: LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 0.)

(It was working, i didn't change anything but just upgraded flutter sdk)

### Expected results

not geting warnings during build and geting geo location data without any error

### Actual results

warnings printed, couldn't get geo location

### Code sample

These warning and error message printed out:

<details><summary>Code sample</summary>

```These warnings printed out to console while building app: 
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:40:31: warning: 'authorizationStatus' is deprecated: first deprecated in macOS 11.0 [-Wdeprecated-declarations]
    return [CLLocationManager authorizationStatus];
                              ^~~~~~~~~~~~~~~~~~~
                              authorizationStatus
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
+ (CLAuthorizationStatus)authorizationStatus API_DEPRECATED_WITH_REPLACEMENT("-authorizationStatus", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:47:65: warning: 'authorizationStatus' is deprecated: first deprecated in macOS 11.0 [-Wdeprecated-declarations]
  CLAuthorizationStatus authorizationStatus = CLLocationManager.authorizationStatus;
                                                                ^~~~~~~~~~~~~~~~~~~
                                                                authorizationStatus
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
+ (CLAuthorizationStatus)authorizationStatus API_DEPRECATED_WITH_REPLACEMENT("-authorizationStatus", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:47:65: warning: 'authorizationStatus' is deprecated: first deprecated in macOS 11.0 [-Wdeprecated-declarations]
  CLAuthorizationStatus authorizationStatus = CLLocationManager.authorizationStatus;
                                                                ^~~~~~~~~~~~~~~~~~~
                                                                authorizationStatus
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
+ (CLAuthorizationStatus)authorizationStatus API_DEPRECATED_WITH_REPLACEMENT("-authorizationStatus", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.m:107:1: warning: implementing deprecated method [-Wdeprecated-implementations]
- (void) locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status {
^
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/PermissionHandler.h:11:
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status API_DEPRECATED_WITH_REPLACEMENT("-locationManagerDidChangeAuthorization:", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^
4 warnings generated.
/Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/LocationServiceStreamHandler.m:36:1: warning: implementing deprecated method [-Wdeprecated-implementations]
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status{
^
In module 'CoreLocation' imported from /Users/o.halukkarakaya/.pub-cache/hosted/pub.dev/geolocator_apple-2.3.7/macos/Classes/Handlers/LocationServiceStreamHandler.m:9:
- (void)locationManager:(CLLocationManager *)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status API_DEPRECATED_WITH_REPLACEMENT("-locationManagerDidChangeAuthorization:", ios(4.2, 14.0), macos(10.7, 11.0), watchos(1.0, 7.0), tvos(9.0, 14.0));
^

2024-07-28 23:45:55.966 MY_PROJECT[19285:307656] LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 0.)
```

</details>

### Screenshots or video

<details>
<summary>Screenshots or video demonstration</summary>

[Upload media here]

</details>

### Version

^12.0.0

### Flutter Doctor output

<details><summary>Doctor output</summary>

```console
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.3, on macOS 14.5 23F79 darwin-x64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.3.7)
[✓] VS Code (version 1.85.0)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!

```

</details>

**Comment by TimHoogstrate** [comment]
Dear @ohalukkarakaya,

Thanks for your input. Regarding the error on macOS. Have you checked if you have an active Wifi connection? Otherwise the Mac cannot determine your location. 

Furthermore, the deprecation warnings should be fixed by us. 

Kind regards,

**Comment by alladyaditi** [comment]
LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 1.)
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: The operation couldn’t be completed. (kCLErrorDomain error 1.)
#0      GeolocatorApple.getPositionStream.<anonymous closure> (package:geolocator_apple/src/geolocator_apple.dart:188:9)
#1      Stream.handleError.<anonymous closure> (dart:async/stream.dart:931:16)
#2      _HandleErrorStream._handleError (dart:async/stream_pipe.dart:269:17)
#3      _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#4      _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#5      _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#6      _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#7      _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:306:7)
#8      _ForwardingStreamSubscription._addError (dart:async/stream_pipe.dart:128:11)
#9      _ForwardingStream._handleError (dart:async/stream_pipe.dart:95:10)
#10     _ForwardingStreamSubscription._handleError (dart:async/stream_pipe.dart:157:13)
#11     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#12     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#13     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#14     _BufferingStreamSubscription._addError (dart:async/stream_impl.dart:306:7)
#15     _SyncBroadcastStreamController._sendError.<anonymous closure> (dart:async/broadcast_stream_controller.dart:392:20)
#16     _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322:15)
#17     _SyncBroadcastStreamController._sendError (dart:async/broadcast_stream_controller.dart:391:5)
#18     _AsBroadcastStreamController.addError (dart:async/broadcast_stream_controller.dart:486:5)
#19     _RootZone.runBinaryGuarded (dart:async/zone.dart:1606:10)
#20     _BufferingStreamSubscription._sendError.sendError (dart:async/stream_impl.dart:384:15)
#21     _BufferingStreamSubscription._sendError (dart:async/stream_impl.dart:402:7)
#22     _DelayedError.perform (dart:async/stream_impl.dart:552:14)
#23     _PendingEvents.handleNext (dart:async/stream_impl.dart:646:11)
#24     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:617:7)
#25     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#26     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5) I am getting the same issue for IOS for geolocator 12.0.0

**Comment by alladyaditi** [comment]
LOCATION UPDATE FAILURE:Error reason: (null)Error description: The operation couldn’t be completed. (kCLErrorDomain error 1.)

**Comment by juliansteenbakker** [comment]
> Thanks for your input. Regarding the error on macOS. Have you checked if you have an active Wifi connection? Otherwise the Mac cannot determine your location.

This error indeed pops up when wifi is disabled. However, the problem is that it does not throw a dart/flutter exception. Because of this, everything freezes. I think this is only on macOS.

```dart
    try {
      return await Geolocator.getCurrentPosition();
    } catch (e) { // Never gets thrown
      debugPrint('$e');
      return null;
    }
```
