### ISSUE TITLE
Error on register plugin in Android

### ISSUE THREAD

**Issue by Thuran** [Baseflow/flutter-geolocator#449]
## 🐛 Bug Report

When android try register plugins, the geolocator registerWith crash application

### Expected behavior
Can register geolocator plugin

### Reproduction steps
Flutter Activity:
```
override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        GeneratedPluginRegistrant.registerWith(flutterEngine)
        val shimPluginRegistry = ShimPluginRegistry(flutterEngine)
        QRCodeScannerPlugin.registerWith(shimPluginRegistry.registrarFor(packageName))
    }
```
Error Stacktrace:
```
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void io.flutter.plugin.common.BinaryMessenger.setMessageHandler(java.lang.String, io.flutter.plugin.common.BinaryMessenger$BinaryMessageHandler)' on a null object reference
        at io.flutter.plugin.common.MethodChannel.setMethodCallHandler(MethodChannel.java:116)
        at com.baseflow.geolocator.GeolocatorPlugin.registerWith(GeolocatorPlugin.java:49)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:20)
        at br.com.codemoney.customer.ui.flutter.CMFlutterActivity.configureFlutterEngine(CMFlutterActivity.kt:99)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:178)
        at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:409)
        at br.com.codemoney.customer.ui.flutter.CMFlutterActivity.onCreate(CMFlutterActivity.kt:84)
        at android.app.Activity.performCreate(Activity.java:6666)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2619)
```

### Configuration

**Version:** ^5.3.1

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@Thuran could you try again using version 5.3.2+2 of the Geolocator plugin?

Also it might be helpful to make sure you project is updated to support the latest Flutter API for Android (which is available since Flutter 1.12). Instructions can be found here: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

Please let me know if this helps.

**Comment by Thuran** [comment]
Yes, it work's.

**Comment by mvanbeusekom** [comment]
Thank you for confirming, closing the issue now.
