### ISSUE TITLE
java.lang.IllegalStateException: Handler (android.location.LocationManager$GnssStatusListenerTransport$GnssHandler) {7798ff5} sending message to a Handler on a dead thread

### ISSUE THREAD

**Issue by loooookiezxc** [Baseflow/flutter-geolocator#487]
I have this class on my project which returns the location of the device. When I ran it on the android emulator there is no problem in getting the current location, also when I'm using other physical devices with dual sim. But when I ran it on my RedMi Note 7 which has dual sim network, it's not working, I tried to disable the other sim, restarted the phone, also I've toggled the airplane mode on and off, it worked but only once, I can't figure out what the problem is. I also saw an exception using the ADB logcat. See below

```javascript
class LocationService {
  final DialogService _dialogService = locator<DialogService>();
  Position _currentPos;
  Position get currentPos => _currentPos;
  Geolocator geolocator = Geolocator()..forceAndroidLocationManager = true;
  Future getCurrentLocation() async {
    try {
      if(await Permission.location.isDenied || await Permission.location.isPermanentlyDenied || await Permission.location.isRestricted ||await Permission.location.isUndetermined ) {
        await Permission.locationAlways.request();
        _currentPos = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
        print(_currentPos);
      } else {
        _currentPos = await geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.best);
        print(_currentPos);
      }
    } catch (e) {
      await _dialogService.showDialog(
        title: 'Location Access Denied',
        description: 'You can turn on your device\'s location on your phone\'s settings.',
      );
      return null;
    }
    
  }

  void showToast(message) {
    Fluttertoast.showToast(
      msg: message,
      toastLength: Toast.LENGTH_SHORT,
      gravity: ToastGravity.BOTTOM,
      timeInSecForIosWeb: 1,
      backgroundColor: Colors.red,
      textColor: Colors.white,
      fontSize: 16.0,
    );
  }
}
```

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.19041.329], locale en-US)
    • Flutter version 1.20.2 at D:\Utilities\flutter
    • Framework revision bbfbf1770c (6 days ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at C:\Users\Development\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java       
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.48.0)
    • VS Code at C:\Users\Development\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.13.2

[√] Connected device (2 available)
    • Redmi Note 7 (mobile)        • 12acda02      • android-arm64 • Android 10 (API 29)
    • AOSP on IA Emulator (mobile) • emulator-5554 • android-x86   • Android 9 (API 28) (emulator)

• No issues found!
```

```
08-19 21:42:37.218  3713  3999 I NetworkLocationManager: start get current Location
08-19 21:42:37.219  3713  3713 I MetokLocationProvider: report position from 2
08-19 21:42:37.493 23005 23005 I subsystem_ramdump: Usage:./system/bin/subsystem_ramdump [arg1] [arg2] [arg3]
08-19 21:42:37.493 23005 23005 I subsystem_ramdump: [arg1]: (1/2) Ramdump location: 1: eMMC: /data/vendor/ramdump or 2: SD card: /sdcard/ramdump
08-19 21:42:37.493 23005 23005 I subsystem_ramdump: [arg2]: (1/0) 1: Enable RPM log / 0: Disable RPM log
08-19 21:42:37.493 23005 23005 I subsystem_ramdump: [arg3]: (1/0) 1: Enable qdss ramdump / 0: Disable qdss ramdump
08-19 21:42:37.493 23005 23005 I subsystem_ramdump:  Using default ramdump location 1: eMMC: /data/vendor/ramdump
08-19 21:42:37.483 23005 23005 W subsystem_ramdu: type=1400 audit(0.0:3860): avc: denied { read } for name="enable_ramdumps" dev="sysfs" ino=25533 scontext=u:r:vendor_subsystem_ramdump:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-19 21:42:37.493 23005 23005 I subsystem_ramdump:  Using default 0: Disable RPM log
08-19 21:42:37.493 23005 23005 I subsystem_ramdump:  Using default 0: Disable qdss ramdump
08-19 21:42:37.493 23005 23005 E subsystem_ramdump: Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
08-19 21:42:37.516  4500  5810 W MessageQueue: Handler (android.location.LocationManager$GnssStatusListenerTransport$GnssHandler) {7798ff5} sending message to a Handler on a dead thread
08-19 21:42:37.516  4500  5810 W MessageQueue: java.lang.IllegalStateException: Handler (android.location.LocationManager$GnssStatusListenerTransport$GnssHandler) {7798ff5} sending message to a Handler on a dead thread
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.MessageQueue.enqueueMessage(MessageQueue.java:561)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Handler.enqueueMessage(Handler.java:754)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Handler.sendMessageAtTime(Handler.java:703)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Handler.sendMessageDelayed(Handler.java:673)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Handler.sendMessage(Handler.java:611)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Message.sendToTarget(Message.java:474)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.location.LocationManager$GnssStatusListenerTransport.onSvStatusChanged(LocationManager.java:1779)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.location.IGnssStatusListener$Stub.onTransact(IGnssStatusListener.java:142)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Binder.execTransactInternal(Binder.java:1021)
08-19 21:42:37.516  4500  5810 W MessageQueue:  at android.os.Binder.execTransact(Binder.java:994)
08-19 21:42:37.734  1941  1975 D HBMFeatureControl: light lux=33.0
08-19 21:42:37.737  2145  2558 D NetworkController.MobileSignalController(1): 4G level = 5
08-19 21:42:37.936  1941  1975 D HBMFeatureControl: light lux=38.0
```

**Comment by mvanbeusekom** [comment]
@loooookiezxc going on the stack trace this seems to be an OS issue. The device's has acquired a location and tried to send it back to the App but encounters a dead thread.

Is the App running in the background? Maybe you can try with our latest release candidate which has different logic on processing the [location updates](https://pub.dev/packages/geolocator/versions/6.0.0-rc.3). And it will specifically assign the main thread to the location fetching process.

**Comment by loooookiezxc** [comment]
Hi @mvanbeusekom, thanks for the response. But this is just the log on the startup of the app where it checks if the current location of the device is inside a google map radius. I am not getting the location in the background. Maybe I should try your suggestion and give feedback later.

**Comment by loooookiezxc** [comment]
Okay, I tried the latest version of the plugin, the prior error seems gone now. But what I've encountered is that the plugin cannot verify what is the state of the location service is. I had my location service enabled before running the app, but the plugin says the location service is not enabled. Again here are the logs from the ADB logcat. Seems like I am doing something wrong.

```
08-29 12:43:13.161 20778 20893 I flutter : ****************************************************
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter : Flutter App Starts Here
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter :
08-29 12:43:13.161 20778 20893 I flutter : *****************************************************************
08-29 12:43:13.174  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.190  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.201  1058  1058 D Zygote  : Forked child process 21855
08-29 12:43:13.192 21855 21855 W main    : type=1400 audit(0.0:63916): avc: granted { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=18820 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file
08-29 12:43:13.207  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.217  1943  1970 D Boost   : hostingType=content provider, hostingName={com.google.android.gsf/com.google.android.gsf.settings.GoogleSettingsProvider}, callerPackage=com.google.android.gms, isSystem=false, isBoostNeeded=false.
08-29 12:43:13.218  1091  1306 D OemNetd : setPidForPackage: packageName=com.google.android.gsf, pid=21855, pid=10161
08-29 12:43:13.218  1943  1970 I ActivityManager: Start proc 21855:com.google.process.gapps/u0a161 for content provider {com.google.android.gsf/com.google.android.gsf.settings.GoogleSettingsProvider} caller=com.google.android.gms
08-29 12:43:13.222 21855 21855 E e.process.gapp: Not starting debugger since process cannot load the jdwp agent.
08-29 12:43:13.224  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.234  1943  1955 D CompatibilityInfo: mCompatibilityFlags - 0
08-29 12:43:13.234  1943  1955 D CompatibilityInfo: applicationDensity - 440
08-29 12:43:13.234  1943  1955 D CompatibilityInfo: applicationScale - 1.0
08-29 12:43:13.240  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.257  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.265 21855 21855 I e.process.gapp: The ClassLoaderContext is a special shared library.
08-29 12:43:13.274  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.276 21855 21855 I Perf    : Connecting to perf service.
08-29 12:43:13.279  2150  2150 D NavBarTintController: onSampleCollected 1.0
08-29 12:43:13.290  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.297 21855 21855 I GoogleHttpClient: GMS http client unavailable, use old client
08-29 12:43:13.307  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.318 21855 21855 I FeatureParser: can't find lavender.xml in assets/device_features/,it may be in /system/etc/device_features
08-29 12:43:13.320 21855 21855 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
08-29 12:43:13.312 21855 21855 W e.process.gapps: type=1400 audit(0.0:63917): avc: denied { read } for name="u:object_r:vendor_displayfeature_prop:s0" dev="tmpfs" ino=18875 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:vendor_displayfeature_prop:s0 tclass=file permissive=0
08-29 12:43:13.322   587   587 I hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.iop@2.0::IIop/default in either framework or device manifest.
08-29 12:43:13.322  1115  1115 E ANDR-IOP: IIop:: Iop HAL Service is not available.
08-29 12:43:13.324 21855 21875 E Perf    : Fail to get file list com.google.android.gsf
08-29 12:43:13.324  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.324 21855 21875 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-29 12:43:13.324 21855 21875 E Perf    : Fail to get file list com.google.android.gsf
08-29 12:43:13.324 21855 21875 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-29 12:43:13.325 21855 21875 E Perf    : Fail to get file list oat
08-29 12:43:13.325 21855 21875 E Perf    : getFolderSize() : Exception_1 = java.lang.NullPointerException: Attempt to get length of null array
08-29 12:43:13.336  1943  3709 I ActivityTaskManager: START u0 {act=com.google.android.gms.location.settings.CHECK_SETTINGS pkg=com.google.android.gms cmp=com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (has extras)} from uid 10161
08-29 12:43:13.337  1943  3709 D ActivityTaskManagerServiceInjector: MIUILOG- Permission Denied Activity : Intent { act=com.google.android.gms.location.settings.CHECK_SETTINGS pkg=com.google.android.gms cmp=com.google.android.gms/com.google.android.location.settings.LocationSettingsCheckerActivity (has extras) } pkg : com.google.android.gms uid : 10161 tuid : 10262
08-29 12:43:13.341  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.357  1872  1872 E Indicator: not support setTranslationX
08-29 12:43:13.360   587   587 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1943 scontext=u:r:system_server:s0 tcontext=u:object_r:hal_srvctracker_hwservice:s0 tclass=hwservice_manager permissive=0
08-29 12:43:13.362  1943  4087 D CompatibilityInfo: mCompatibilityFlags - 0
08-29 12:43:13.362  1943  4087 D CompatibilityInfo: applicationDensity - 440
08-29 12:43:13.362  1943  4087 D CompatibilityInfo: applicationScale - 1.0
08-29 12:43:13.363   587   587 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1943 scontext=u:r:system_server:s0 tcontext=u:object_r:hal_srvctracker_hwservice:s0 tclass=hwservice_manager permissive=0
````

**Comment by loooookiezxc** [comment]
=======Update=======
I have found out that the prior error which is that it cannot get the current status of the location service only appears when I am using the mobile network for geolocation, when I'm on wifi it works fine but goes back to the first issue that I've posted earlier.

I'm so fed up with Chinese brand phones as it complicates things like this. Please, I need help.

**Comment by mvanbeusekom** [comment]
@loooookiezxc you code looks good. Regarding the location services, from the logs I see that geolocator tries to verify if the required settings are correctly set, which is a feature from the Google Play Services. However somehow Android is failing to find or get access to some of the needed vendor libraries:

```
08-29 12:43:13.320 21855 21855 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
...
...
08-29 12:43:13.360   587   587 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1943 scontext=u:r:system_server:s0 tcontext=u:object_r:hal_srvctracker_hwservice:s0 tclass=hwservice_manager permissive=0
```

This really makes me believe this is an device / vendor software problem. Maybe something you could try is to use force the Android LocationManager (maybe parts of the Google Play Services are not available for the RedMi due to the trade embargo issues between Trump and China). You could do so by calling the `getCurrentPosition` method like this:

```
      _currentPos = await getCurrentPosition(
          desiredAccuracy: LocationAccuracy.best,
          forceAndroidLocationManager: true);
``` 

I don't see anything wrong in the snippet you posted. Unfortunately I don't have access to a RedMi Note 7 which makes it difficult for me to reproduce the problem (since for me it also simply works on the emulator and my Android devices, LG Nexus 5x and Samsung Galaxy S9). 

Hope this helps a little bit.

**Comment by loooookiezxc** [comment]
@mvanbeusekom sorry if I'm giving a headache. Your suggestion gives me a little breathing room, prior errors are now gone. But still, it's not working and there is something I've noticed on the log. Please tell me what do you think about this. Will this make you conclude that it is indeed a problem or a bug on the device provider itself?

```
08-29 20:03:45.746  3495  4500 I BehaviorRecord-Monitor: com.taraphilippines.orderingapp , perm: 32 , operation 2 , current size: 1 , foreground com.taraphilippines.orderingapp
08-29 20:03:45.746  1943  1958 I GnssLocationProvider: GNSS HAL Requesting location updates from network provider for 10000 millis.
08-29 20:03:45.747  3729  4282 I MetokLocationProvider: onSetRequest
08-29 20:03:45.748  3729  3729 I MetokLocationProvider: setRequest: request =ProviderRequest[ON interval=+1s0ms] ; client =WorkSource{1000 android}
08-29 20:03:45.750  2150  2150 D SignalClusterView: updateMobileTypeImage  0
08-29 20:03:45.767  2150  2150 D SignalClusterView: updateMobileTypeImage  0
08-29 20:03:45.769  2150  2150 D NavBarTintController: onSampleCollected 1.0
08-29 20:03:45.787  1943  4846 I WifiService: startScan uid=10107
08-29 20:03:45.787  1943  2078 D MiuiScanRequestProxy: Package com.xiaomi.metoknlp is in white list
08-29 20:03:45.788  1943  2078 E WifiScanRequestProxy: Scan failure received. reason: -1,description: not available
08-29 20:03:45.788  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:45.791  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:45.791  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:45.792  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:45.882  2150  2150 D NavBarTintController: onSampleCollected 1.0
08-29 20:03:46.000  2150  2150 D NavBarTintController: onSampleCollected 1.0
08-29 20:03:46.712  2150  2604 D NetworkController.MobileSignalController(1): 4G level = 5
08-29 20:03:46.835  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:46.836  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:47.360  4559  4559 I subsystem_ramdump: Usage:./system/bin/subsystem_ramdump [arg1] [arg2] [arg3]
08-29 20:03:47.360  4559  4559 I subsystem_ramdump: [arg1]: (1/2) Ramdump location: 1: eMMC: /data/vendor/ramdump or 2: SD card: /sdcard/ramdump
08-29 20:03:47.360  4559  4559 I subsystem_ramdump: [arg2]: (1/0) 1: Enable RPM log / 0: Disable RPM log
08-29 20:03:47.360  4559  4559 I subsystem_ramdump: [arg3]: (1/0) 1: Enable qdss ramdump / 0: Disable qdss ramdump
08-29 20:03:47.360  4559  4559 I subsystem_ramdump:  Using default ramdump location 1: eMMC: /data/vendor/ramdump
08-29 20:03:47.360  4559  4559 I subsystem_ramdump:  Using default 0: Disable RPM log
08-29 20:03:47.342  4559  4559 W subsystem_ramdu: type=1400 audit(0.0:68673): avc: denied { read } for name="enable_ramdumps" dev="sysfs" ino=25533 scontext=u:r:vendor_subsystem_ramdump:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-29 20:03:47.360  4559  4559 I subsystem_ramdump:  Using default 0: Disable qdss ramdump
08-29 20:03:47.360  4559  4559 E subsystem_ramdump: Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
08-29 20:03:47.877  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:47.877  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:48.930  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:48.931  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:49.691  2150  2604 D NetworkController.MobileSignalController(1): 4G level = 5
08-29 20:03:49.943  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:49.943  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:50.814  3200  3229 W dix.fingerprin: Reducing the number of considered missed Gc histogram windows from 103 to 100
08-29 20:03:50.991  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:50.992  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:51.933  2150  2604 D NetworkController.MobileSignalController(1): 4G level = 5
08-29 20:03:52.040  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:52.041  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:52.365  4561  4561 I subsystem_ramdump: Usage:./system/bin/subsystem_ramdump [arg1] [arg2] [arg3]
08-29 20:03:52.365  4561  4561 I subsystem_ramdump: [arg1]: (1/2) Ramdump location: 1: eMMC: /data/vendor/ramdump or 2: SD card: /sdcard/ramdump
08-29 20:03:52.365  4561  4561 I subsystem_ramdump: [arg2]: (1/0) 1: Enable RPM log / 0: Disable RPM log
08-29 20:03:52.365  4561  4561 I subsystem_ramdump: [arg3]: (1/0) 1: Enable qdss ramdump / 0: Disable qdss ramdump
08-29 20:03:52.365  4561  4561 I subsystem_ramdump:  Using default ramdump location 1: eMMC: /data/vendor/ramdump
08-29 20:03:52.365  4561  4561 I subsystem_ramdump:  Using default 0: Disable RPM log
08-29 20:03:52.365  4561  4561 I subsystem_ramdump:  Using default 0: Disable qdss ramdump
08-29 20:03:52.365  4561  4561 E subsystem_ramdump: Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
08-29 20:03:52.352  4561  4561 W subsystem_ramdu: type=1400 audit(0.0:68674): avc: denied { read } for name="enable_ramdumps" dev="sysfs" ino=25533 scontext=u:r:vendor_subsystem_ramdump:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-29 20:03:52.845  4524  4545 I .android.camer: ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
08-29 20:03:53.096  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:53.097  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:54.151  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:54.152  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:55.206  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:55.207  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:55.748  1943  1958 I GnssLocationProvider: Removing location updates from network provider.
08-29 20:03:55.749  1943  1958 I GnssLocationProvider: GNSS HAL Requesting location updates from network provider for 10000 millis.
08-29 20:03:55.749  3729  8226 I MetokLocationProvider: onSetRequest
08-29 20:03:55.749  3729  3729 I MetokLocationProvider: setRequest: request =ProviderRequest[OFF] ; client =WorkSource{}
08-29 20:03:55.749  3729  3729 I NLPWrapper: request exit
08-29 20:03:55.750  3729  8226 I MetokLocationProvider: onSetRequest
08-29 20:03:55.750  3729  3729 I MetokLocationProvider: setRequest: request =ProviderRequest[ON interval=+1s0ms] ; client =WorkSource{1000 android}
08-29 20:03:55.751  2150  2604 D NetworkController.MobileSignalController(1): 4G level = 5
08-29 20:03:55.752  1943  4846 I WifiService: startScan uid=10107
08-29 20:03:55.753  1943  2078 D MiuiScanRequestProxy: Package com.xiaomi.metoknlp is in white list
08-29 20:03:55.753  1943  2078 E WifiScanRequestProxy: Scan failure received. reason: -1,description: not available
08-29 20:03:55.755  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:55.793  3729  3729 I MetokLocationProvider: report position from 6
08-29 20:03:55.795  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:03:55.795  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:03:55.816  1943  3688 W DevicePolicyManager: Package com.xiaomi.metoknlp (uid=10107, pid=3729) cannot access Device IDs
08-29 20:03:55.817  2377  2401 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.xiaomi.metoknlp:getDeviceId:isPreinstalled=true:isPrivApp=false
08-29 20:03:55.834  1943  3688 W DevicePolicyManager: Package com.xiaomi.metoknlp (uid=10107, pid=3729) cannot access Device IDs
08-29 20:03:55.835  2377  2401 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.xiaomi.metoknlp:getDeviceId:isPreinstalled=true:isPrivApp=false
08-29 20:03:55.851  1943  3688 W DevicePolicyManager: Package com.xiaomi.metoknlp (uid=10107, pid=3729) cannot access Device IDs
08-29 20:03:55.852  2377  2401 W TelephonyPermissions: reportAccessDeniedToReadIdentifiers:com.xiaomi.metoknlp:getSubscriberId:isPreinstalled=true:isPrivApp=false
08-29 20:03:55.852  3729  4562 W System  : Ignoring header MIUICVER because its value was null.
08-29 20:03:55.852  3729  4562 W System  : Ignoring header MIUIPVER because its value was null.
08-29 20:14:49.394  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:49.395  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:49.395  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:49.396  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:50.483  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:50.484  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:51.532  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:51.533  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:52.585  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:52.586  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:52.906   587   587 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1943 scontext=u:r:system_server:s0 tcontext=u:object_r:hal_srvctracker_hwservice:s0 tclass=hwservice_manager permissive=0
08-29 20:14:53.010  1943  1969 I ActivityManager: Waited long enough for: ServiceRecord{d35eecf u0 com.google.android.gms/.gcm.GcmService}
08-29 20:14:52.909   587   587 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1943 scontext=u:r:system_server:s0 tcontext=u:object_r:hal_srvctracker_hwservice:s0 tclass=hwservice_manager permissive=0
08-29 20:14:53.293  5517  5517 I subsystem_ramdump: Usage:./system/bin/subsystem_ramdump [arg1] [arg2] [arg3]
08-29 20:14:53.293  5517  5517 I subsystem_ramdump: [arg1]: (1/2) Ramdump location: 1: eMMC: /data/vendor/ramdump or 2: SD card: /sdcard/ramdump
08-29 20:14:53.293  5517  5517 I subsystem_ramdump: [arg2]: (1/0) 1: Enable RPM log / 0: Disable RPM log
08-29 20:14:53.293  5517  5517 I subsystem_ramdump: [arg3]: (1/0) 1: Enable qdss ramdump / 0: Disable qdss ramdump
08-29 20:14:53.293  5517  5517 I subsystem_ramdump:  Using default ramdump location 1: eMMC: /data/vendor/ramdump
08-29 20:14:53.293  5517  5517 I subsystem_ramdump:  Using default 0: Disable RPM log
08-29 20:14:53.293  5517  5517 I subsystem_ramdump:  Using default 0: Disable qdss ramdump
08-29 20:14:53.293  5517  5517 E subsystem_ramdump: Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
08-29 20:14:53.282  5517  5517 W subsystem_ramdu: type=1400 audit(0.0:68827): avc: denied { read } for name="enable_ramdumps" dev="sysfs" ino=25533 scontext=u:r:vendor_subsystem_ramdump:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-29 20:14:53.458   587   587 E SELinux : avc:  denied  { find } for interface=vendor.qti.hardware.servicetracker::IServicetracker sid=u:r:system_server:s0 pid=1943 scontext=u:r:system_server:s0 tcontext=u:object_r:hal_srvctracker_hwservice:s0 tclass=hwservice_manager permissive=0
08-29 20:14:53.628  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:53.628  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:54.683  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:54.684  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:54.980  2150  2604 D NetworkController.MobileSignalController(1): 4G level = 5
08-29 20:14:55.736  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:55.737  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:56.792  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:56.793  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:57.845  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:57.846  3729  3729 I MetokLocationProvider: report position from 2
08-29 20:14:58.301  5518  5518 I subsystem_ramdump: Usage:./system/bin/subsystem_ramdump [arg1] [arg2] [arg3]
08-29 20:14:58.301  5518  5518 I subsystem_ramdump: [arg1]: (1/2) Ramdump location: 1: eMMC: /data/vendor/ramdump or 2: SD card: /sdcard/ramdump
08-29 20:14:58.301  5518  5518 I subsystem_ramdump: [arg2]: (1/0) 1: Enable RPM log / 0: Disable RPM log
08-29 20:14:58.301  5518  5518 I subsystem_ramdump: [arg3]: (1/0) 1: Enable qdss ramdump / 0: Disable qdss ramdump
08-29 20:14:58.292  5518  5518 W subsystem_ramdu: type=1400 audit(0.0:68828): avc: denied { read } for name="enable_ramdumps" dev="sysfs" ino=25533 scontext=u:r:vendor_subsystem_ramdump:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-29 20:14:58.301  5518  5518 I subsystem_ramdump:  Using default ramdump location 1: eMMC: /data/vendor/ramdump
08-29 20:14:58.301  5518  5518 I subsystem_ramdump:  Using default 0: Disable RPM log
08-29 20:14:58.301  5518  5518 I subsystem_ramdump:  Using default 0: Disable qdss ramdump
08-29 20:14:58.301  5518  5518 E subsystem_ramdump: Unable to open /sys/module/subsystem_restart/parameters/enable_ramdumps
08-29 20:14:58.893  3729  4109 I NetworkLocationManager: start get current Location
08-29 20:14:58.894  3729  3729 I MetokLocationProvider: report position from 2
```

As you can see the plugin retries to get the current location several times.

**Comment by loooookiezxc** [comment]
========Update========
I just let the phone still for a while, while reading the logs on adb logcat. I don't understand why, but after about 10 it the plugin returns the location of the device. I am clueless now. For real.

**Comment by mvanbeusekom** [comment]
@loooookiezxc which permissions do you have in your `AndroidManifest.xml` file? We know that if you only have `ACCESS_COARSE_LOCATION` Android will only use the cellular network to determine the device's location and this can take a long time. 

If this is the case in your setup, you could try also adding the `ACCESS_FINE_LOCATION` permission which makes sure Android will also use the GPS chip to get hold of the device's location.

**Comment by loooookiezxc** [comment]
Hello @mvanbeusekom yes I've also added the ```ACCESS_FINE_LOCATION``` permission. I'm starting to get familiarized with the plugin, one thing I noticed is that on some devices, especially the ones came Chinese manufacturers, when getting the location and setting the ```LocationAccuracy``` to other but medium, the plugin cannot return the current location, so I'm stuck with using only ```LocationAccuracy.medium```. I'm still trying to look for the cause of this behavior. Or do you have any idea why is this happening?

**Comment by loooookiezxc** [comment]
Also, I saw deprecation warnings on the plugin, the one came from the LocationClientManager.java file, It says that the ```LocationProvider.AVAILABLE``` is deprecated. Might refer as well to this link https://developer.android.com/reference/android/location/LocationProvider

**Comment by loooookiezxc** [comment]
Hey, @mvanbeusekom I'll be closing this issue. I know now what is the cause of my problem. But I will open another thread regarding all the use cases I've experienced instead and maybe this can help you to enhance the geolocator plugin. Thanks for all the help :)

**Comment by mvanbeusekom** [comment]
Hi @loooookiezxc, I am very much looking forward at your other thread / issue as this information is very valuable to me. Especially since I don't have access to all these different devices and their quarks and your willingness to endure all the effort helping me to improve the plugin.

At this very moment I am working on a new release to solve some smaller issues (like the deprecation warning you mentioned and some documentation updates), I will hopefully be able to release that tomorrow morning.

Let me finish by thanking you for the great and detailed feedback!
