### ISSUE TITLE
Unable to convert the value "4" into a LocationPermission.

### ISSUE THREAD

**Issue by Theunodb** [Baseflow/flutter-geolocator#493]
## 🐛 Bug Report

When asking for permission on an iOS simulator i get an error stating
"Unable to convert the value "4" into a LocationPermission."

```
Unhandled Exception: Unable to convert the value "4" into a LocationPermission.
#0      IntergerExtensions.toLocationPermission (package:geolocator_platform_interface/src/extensions/integer_extensions.dart:21:9)
#1      MethodChannelGeolocator.checkPermission (package:geolocator_platform_interface/src/implementations/method_channel_geolocator.dart:43:25)
<asynchronous suspension>
#2      checkPermission (package:geolocator/geolocator.dart:10:33)
#3      LocationCubit.locationStarted (package:trigger/blocs/location/location_cubit.dart:45:39)
#4      _HomeScreenState.build.<anonymous closure> (package:trigger/ui/home/home_screen.dart:200:31)
#5      _BlocListenerBaseState._subscribe.<anonymous closure> (package:flutter_bloc/src/bloc_listener.dart:187:26)
#6      _rootRunUnary (dart:async/zone.dart:1198:47)
#7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#9      _BufferingStreamSubscription._s<…>
```

```
[✓] Flutter (Channel master, 1.22.0-2.0.pre.135, on Mac OS X 10.15.6 19G2021,
    locale en-ZA)
    • Flutter version 1.22.0-2.0.pre.135 at /Users/theunodebruin/flutter
    • Framework revision 8fa5c55e54 (9 hours ago), 2020-08-30 19:05:20 -0700
    • Engine revision 1e302a111d
    • Dart version 2.10.0 (build 2.10.0-76.0.dev)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/theunodebruin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Users/theunodebruin/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/theunodebruin/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android
      Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.2.1)
    • IntelliJ at /Users/theunodebruin/Applications/JetBrains Toolbox/IntelliJ
      IDEA Ultimate.app
    • Flutter plugin version 48.1.4
    • Dart plugin version 202.7206

[✓] Connected device (1 available)
    • iPhone 11 Pro Max (mobile) • 58A3D0FB-E854-4A3A-9C98-D487010ACB57 • ios •
      com.apple.CoreSimulator.SimRuntime.iOS-13-6 (simulator)
```

**Comment by mvanbeusekom** [comment]
@Theunodb good find, thank you very much for reporting it. I have fixed the issue and released a hotfix (6.0.0+1) which should now solve the problem.
