### ISSUE TITLE
Failed to handle method call

### ISSUE THREAD

**Issue by humazed** [Baseflow/flutter-geolocator#511]
## 🐛 Bug Report

In the sample app `LastKnownLocationExampleWidget` deny the permission close and reopen the app  I get the following exception and the app crashes.

```W/Activity(27768): Can request only one set of permissions at a time
E/MethodChannel#flutter.baseflow.com/geolocator(27768): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/geolocator(27768): java.lang.ArrayIndexOutOfBoundsException: length=0; index=-1
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.baseflow.geolocator.permission.PermissionManager.onRequestPermissionsResult(PermissionManager.java:131)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:664)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.embedding.engine.FlutterEnginePluginRegistry.onRequestPermissionsResult(FlutterEnginePluginRegistry.java:364)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:573)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.embedding.android.FlutterActivity.onRequestPermissionsResult(FlutterActivity.java:602)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at android.app.Activity.requestPermissions(Activity.java:5083)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.baseflow.geolocator.permission.PermissionManager.requestPermission(PermissionManager.java:93)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.baseflow.geolocator.location.GeolocationManager.handlePermissions(GeolocationManager.java:122)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.baseflow.geolocator.location.GeolocationManager.getLastKnownPosition(GeolocationManager.java:38)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onGetLastKnownPosition(MethodCallHandlerImpl.java:145)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:61)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at android.os.Looper.loop(Looper.java:174)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/MethodChannel#flutter.baseflow.com/geolocator(27768): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Version:** 6.0.0+2

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @humazed,

Thank you for reporting this bug. This is a bit of a strange case since for some reason the `onPermissionRequestResult` method is called by the Android OS without any permission results which technically shouldn't happen.

I have however added an extra check for this case to make sure the application won't crash and will simply report that permissions are denied. This is all added in version 6.0.0+3 of the geolocator plugin which I have just released.

Hope you will no longer see this error popping up again ;).
