### ISSUE TITLE
I'm using geolocator plugin in my Flutter project facing this issue while building the app

### ISSUE THREAD

**Issue by aditya305** [Baseflow/flutter-geolocator#517]
How can I solve this?? 

![2020-09-07](https://user-images.githubusercontent.com/41361167/92401853-2f348100-f14c-11ea-86a3-15d3919abd5f.jpg)

**Comment by mvanbeusekom** [comment]
@aditya305 could you send me the complete text version of this log? From the photo you send me I cannot see the whole stack trace and determine what's your problem.

**Comment by aditya305** [comment]
Yes

**Comment by mvanbeusekom** [comment]
I guess you'll be posting them later?

**Comment by aditya305** [comment]
Running Gradle task 'assembleDebug'...
* What went wrong:
Running Gradle task 'assembleDebug'...
Execution failed for task ':geolocator:extractDebugAnnotations'.
Running Gradle task 'assembleDebug'...
> Lint infrastructure error
Running Gradle task 'assembleDebug'...
  Caused by: java.lang.reflect.InvocationTargetException
Running Gradle task 'assembleDebug'...
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Running Gradle task 'assembleDebug'...
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Running Gradle task 'assembleDebug'...
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Running Gradle task 'assembleDebug'...
        at java.lang.reflect.Method.invoke(Method.java:498)
Running Gradle task 'assembleDebug'...
        at com.android.tools.lint.gradle.api.ReflectiveLintRunner.extractAnnotations(ReflectiveLintRunner.kt:64)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.tasks.ExtractAnnotations.doTaskAction(ExtractAnnotations.java:233)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
Running Gradle task 'assembleDebug'...
        at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:34) 
Running Gradle task 'assembleDebug'...
        at sun.reflect.GeneratedMethodAccessor556.invoke(Unknown Source)
Running Gradle task 'assembleDebug'...
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Running Gradle task 'assembleDebug'...
        at java.lang.reflect.Method.invoke(Method.java:498)     
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
Running Gradle task 'assembleDebug'...
        at java.util.Optional.orElseGet(Optional.java:267)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)      
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)    
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)    
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)      
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)        
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)        
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)   
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
Running Gradle task 'assembleDebug'...
        at java.util.Optional.map(Optional.java:215)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)      
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)      
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)     
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
Running Gradle task 'assembleDebug'...
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
Running Gradle task 'assembleDebug'...
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)  
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Running Gradle task 'assembleDebug'...
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Running Gradle task 'assembleDebug'...
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Running Gradle task 'assembleDebug'...
        at java.lang.Thread.run(Thread.java:748)
Running Gradle task 'assembleDebug'...
  Caused by: java.lang.NoClassDefFoundError: com/android/tools/lint/LintCoreApplicationEnvironment
Running Gradle task 'assembleDebug'...
        at com.android.tools.lint.gradle.LintExtractAnnotations.extractAnnotations(LintExtractAnnotations.kt:42)
Running Gradle task 'assembleDebug'...
        ... 106 more
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Try:
Running Gradle task 'assembleDebug'...
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
* Get more help at https://help.gradle.org
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'...
BUILD FAILED in 6m 22s
Running Gradle task 'assembleDebug'...

Running Gradle task 'assembleDebug'... Done                       393.0s (!)
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by aditya305** [comment]
> I guess you'll be posting them later?

Sorry for the delay.

**Comment by mvanbeusekom** [comment]
Another question to get a full overview. Could you send me the contents of the `android/build.gradle` file?

**Comment by aditya305** [comment]
Yes but somehow issue is solved. Thanks for the quick response! :)

**Comment by Raorakshith** [comment]
Can you guide me how did you solved the issue as even I am facing the same

**Comment by aditya305** [comment]
Check the Android/build.gradle change build version according to plugin support. But first read the plug-in docs
