### ISSUE TITLE
IllegalArgumentException: Can only use lower 16 bits for requestCode

### ISSUE THREAD

**Issue by ertong** [Baseflow/flutter-geolocator#590]
## 🐛 Bug Report

In some circumstances, it is possible to see Exception like this:
```
Fatal Exception: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
       at androidx.fragment.app.d.F(:10)
       at androidx.fragment.app.d.startIntentSenderForResult(:7)
       at com.google.android.gms.common.api.Status.n(:19)
       at com.google.android.gms.common.api.i.b(:2)
       at c.b.a.m.j.o(:23)   
       at c.b.a.m.b.d(:8)
       at c.d.a.b.i.u.run(:27)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:201)
       at android.app.ActivityThread.main(ActivityThread.java:6810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```
c.b.a.m.j.o(:23)   looks like points to FusedLocationClient:160 `rae.startResolutionForResult(activity, activityRequestCode);`

If this is the case, we should not initialize `activityRequestCode` as `this.hashCode();` because, obviously, it uses more than 16bits.

**Version:** 6.1.5

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
@corcoran I have just release version 6.1.7 which contains the fix for this issue. Thanks again for reporting.
