### ISSUE TITLE
java.lang.IllegalArgumentException: Service not registered: ls@f0f0fc4

### ISSUE THREAD

**Issue by naveenbharadwaj19** [Baseflow/flutter-geolocator#634]
### Current behavior

```
error in debug console after installing geolocator: ^6.1.13
W/ConnectionTracker(29570): Exception thrown while unbinding
W/ConnectionTracker(29570): java.lang.IllegalArgumentException: Service not registered: ls@f0f0fc4
W/ConnectionTracker(29570): 	at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1751)
W/ConnectionTracker(29570): 	at android.app.ContextImpl.unbindService(ContextImpl.java:1776)
W/ConnectionTracker(29570): 	at android.content.ContextWrapper.unbindService(ContextWrapper.java:741)
W/ConnectionTracker(29570): 	at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):1)
W/ConnectionTracker(29570): 	at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204713084@20.47.13 (120700-0):2)
```

`pubspec.yaml`
```
firebase_auth: ^0.18.3
firebase_core: ^0.5.2
geocoder: ^0.2.1
geolocator: ^6.1.13
```

`build.gradle`
```
compileSdkVersion 30
dependencies {
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
  implementation platform('com.google.firebase:firebase-bom:26.0.0')
  implementation 'com.google.android.gms:play-services-basement:17.5.0'
  implementation 'com.google.firebase:firebase-analytics:18.0.0'
  implementation 'com.google.firebase:firebase-analytics'
  implementation 'androidx.multidex:multidex:2.0.1'
}
```

`output of flutter doctor -v`
```
[√] Flutter (Channel beta, 1.23.0-18.1.pre, on Microsoft Windows [Version 10.0.19041.685], locale en-IN)
    • Flutter version 1.23.0-18.1.pre at D:\OTHER FILES D\CS ALL FOLD\Flutter main sdk\flutter
    • Framework revision 198df796aa (10 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3) 
    • Android SDK at D:\Android_SDK
    • Platform android-30, build-tools 29.0.3
    • ANDROID_HOME = D:\Android_SDK
    • Java binary at: D:\Android studio main\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at D:\Android studio main
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.52.1)
    • VS Code at C:\Users\bhara\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.17.0

[√] Connected device (4 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86    • Android 10 (API 29) (emulator)
    • Web Server (web)                   • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                       • chrome        • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                         • edge          • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```
I think this bug is not related to https://github.com/FirebaseExtended/flutterfire/issues/4090

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
According to the [FirebaseExtended team](https://github.com/FirebaseExtended/flutterfire/issues/4090#issuecomment-738602372) this is an issue with the Firebase Android SDK (firebase/firebase-android-sdk#1662) and not related to the geolocator nor the FirebaseExtended plugins. 

As mentioned this is a non-fatal error and is simply logged as warning (hence the `W/` indicator). The advice from the FirebaseExtended team is to simple ignore the warning.

**Comment by flutterq** [comment]
[[Solved] Exception thrown while unbinding, java.lang.IllegalArgumentException: Service not registered in Flutter
](https://fluttercorner.com/exception-thrown-while-unbinding-java-lang-illegalargumentexception-service-not/)
