### ISSUE TITLE
Fatal Exception on extending MainActivity from FlutterFragmentActivity 

### ISSUE THREAD

**Issue by thakurkartik1901** [Baseflow/flutter-geolocator#654]
The app crashes on Android with the following stack trace:

Fatal Exception: java.lang.IllegalArgumentException: Can only use lower 16 bits for requestCode
       at androidx.fragment.app.FragmentActivity.checkForValidRequestCode(FragmentActivity.java:715)
       at androidx.fragment.app.FragmentActivity.startIntentSenderForResult(FragmentActivity.java:687)
       at com.google.android.gms.common.api.Status.startResolutionForResult(com.google.android.gms:play-services-basement@@17.5.0:26)
       at com.google.android.gms.common.api.ResolvableApiException.startResolutionForResult(com.google.android.gms:play-services-basement@@17.5.0:3)
       at com.baseflow.geolocator.location.FusedLocationClient.lambda$startPositionUpdates$3$FusedLocationClient(FusedLocationClient.java:160)
       at com.baseflow.geolocator.location.-$$Lambda$FusedLocationClient$glHFxMhTP4LzAXPZqXLaFgLu8Vo.onFailure(:8)
       at com.google.android.gms.tasks.zzk.run(com.google.android.gms:play-services-tasks@@17.1.0:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.1.0:6)
       at android.os.Looper.loop(Looper.java:254)
       at android.app.ActivityThread.main(ActivityThread.java:8182)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)

FragmentActivity requires the requestCode to be of 16 bits, meaning the range is from 0 to 65535.

**Comment by mvanbeusekom** [comment]
@thakurkartik1901 which version of the geolocator plugin are you using? This has been a problem and has been solved in version 6.1.7 of the geolocator plugin.

**Comment by thakurkartik1901** [comment]
I was using geolocator: ^6.1.5.
I will update. Thanx for the info @mvanbeusekom
