### ISSUE TITLE
java.lang.NullPointerException when using geolocator

### ISSUE THREAD

**Issue by freewebwithme** [Baseflow/flutter-geolocator#755]
Hi
I have following error message in debug console 

```
E/LocationManager(29679): [LGNSS] encryption lat/lon fail.
W/System.err(29679): java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] javax.crypto.Cipher.doFinal(byte[])' on a null object reference
W/System.err(29679): 	at android.location.LocationManager.encryptionLatLon(LocationManager.java:2508)
W/System.err(29679): 	at android.location.Location.toString(Location.java:1048)
W/System.err(29679): 	at java.lang.String.valueOf(String.java:2896)
W/System.err(29679): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
W/System.err(29679): 	at com.onesignal.GMSLocationController$LocationUpdateListener.onLocationChanged(GMSLocationController.java:181)
W/System.err(29679): 	at com.google.android.gms.internal.location.zzay.notifyListener(Unknown Source:4)
W/System.err(29679): 	at com.google.android.gms.common.api.internal.ListenerHolder.notifyListenerInternal(com.google.android.gms:play-services-base@@17.4.0:18)
W/System.err(29679): 	at com.google.android.gms.common.api.internal.ListenerHolder$zaa.handleMessage(com.google.android.gms:play-services-base@@17.4.0:6)
W/System.err(29679): 	at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err(29679): 	at android.os.Looper.loop(Looper.java:193)
W/System.err(29679): 	at android.app.ActivityThread.main(ActivityThread.java:6854)
W/System.err(29679): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(29679): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
W/System.err(29679): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)

```

Can anyone give some hints for this error?

**Comment by florissmit1** [comment]
Can you provide a code snippet? In what context are you using Geolocator f.e. which method throws this error? Also, provide your `flutter doctor -v`.

**Comment by mvanbeusekom** [comment]
Hi @freewebwithme, according to the line below in the supplied stack trace the exception originates from the OneSignal-Flutter-SDK:

```
at com.onesignal.GMSLocationController$LocationUpdateListener.onLocationChanged(GMSLocationController.java:181)
```

Having a closer look you will see that the OneSignal-Flutter-SDK has a dependency on the OneSignal-Android-SDK which contains the `GMSLocationController` class and indeed has [the line](https://github.com/OneSignal/OneSignal-Android-SDK/blob/c97b07e064de31542b9c79c10370441d4abe45a7/OneSignalSDK/onesignal/src/main/java/com/onesignal/GMSLocationController.java#L181) mentioned in the stack trace.

Since the exception doesn't originate from the geolocator plugin I will close this issue.
