### ISSUE TITLE
permission_handler crash if deny permission in Android settings

### ISSUE THREAD

**Issue by goldenplan** [Baseflow/flutter-geolocator#815]
Version 8.1.4+2

If I go from my application to the application settings by link in android and there for any previously granted permission I select-Prohibit. That application crashes when you try to return to app. I attach the log. I have always checked on the example of permissions related to the camera and location.
Sample link code to location permission settings: 
val action = Settings.ACTION_LOCATION_SOURCE_SETTINGS
startActivity(this as Activity,Intent(action).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK),null)
        

2021-08-18 19:40:47.481 1363-1363/family E/AndroidRuntime: FATAL EXCEPTION: main
    Process: family, PID: 1363
    java.lang.RuntimeException: Unable to resume activity {com.family/com.family.MainActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.family/com.family.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4444)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=24, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com..family/com..family.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5015)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4431)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
        at com.baseflow.permissionhandler.PermissionManager.onRequestPermissionsResult(PermissionManager.java:136)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry$FlutterEngineActivityPluginBinding.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:712)
        at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.onRequestPermissionsResult(FlutterEngineConnectionRegistry.java:412)
        at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onRequestPermissionsResult(FlutterActivityAndFragmentDelegate.java:627)
        at io.flutter.embedding.android.FlutterFragment.onRequestPermissionsResult(FlutterFragment.java:723)
        at io.flutter.embedding.android.FlutterFragmentActivity.onRequestPermissionsResult(FlutterFragmentActivity.java:492)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8466)
        at android.app.Activity.dispatchActivityResult(Activity.java:8314)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5008)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4431) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2021-08-18 19:40:47.484 1363-1514/com.family I/flutter: Observatory listening on http://127.0.0.1:43178/tXDR-VvPFZI=/
2021-08-18 19:40:47.492 1363-1363/com.family I/Process: Sending signal. PID: 1363 SIG: 9

**Comment by mvanbeusekom** [comment]
Hi @goldenplan,

I think you created the issue on the wrong plugin repository (geolocator instead of permission_handler). This is a known issue however and is documented in issues baseflow/flutter-permission-handler#653 and baseflow/flutter-permission-handler#654.

Please have a look there and leave a comment on one of these issues if you have further questions. I will be closing this issue now.
