### ISSUE TITLE
Sometimes in logs we can see NPE

### ISSUE THREAD

**Issue by Andrushka1012** [Baseflow/flutter-geolocator#899]
Our testers reported that sometimes in logs they can see npe. Looks like it happens when we trying to get location first time after user give us all required permissions:
 
```
MethodChannel#flutter.baseflow.com/geolocator: Failed to handle method call
MethodChannel#flutter.baseflow.com/geolocator: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Enum.ordinal()' on a null object reference
MethodChannel#flutter.baseflow.com/geolocator:         at c.b.a.l.a(Unknown Source:13)
MethodChannel#flutter.baseflow.com/geolocator:         at c.b.a.l.G(Unknown Source:111)
MethodChannel#flutter.baseflow.com/geolocator:         at e.a.c.a.j$a.a(Unknown Source:17)
MethodChannel#flutter.baseflow.com/geolocator:         at io.flutter.embedding.engine.e.b.e(Unknown Source:57)
MethodChannel#flutter.baseflow.com/geolocator:         at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
MethodChannel#flutter.baseflow.com/geolocator:         at android.os.MessageQueue.nativePollOnce(Native Method)
MethodChannel#flutter.baseflow.com/geolocator:         at android.os.MessageQueue.next(MessageQueue.java:335)
MethodChannel#flutter.baseflow.com/geolocator:         at android.os.Looper.loop(Looper.java:206)
MethodChannel#flutter.baseflow.com/geolocator:         at android.app.ActivityThread.main(ActivityThread.java:8595)
MethodChannel#flutter.baseflow.com/geolocator:         at java.lang.reflect.Method.invoke(Native Method)
MethodChannel#flutter.baseflow.com/geolocator:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
MethodChannel#flutter.baseflow.com/geolocator:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by mvanbeusekom** [comment]
Hi @Andrushka1012, thank you for submitting this bug report. Could you please provide some more information?

I am particularly interested in the following:
1. The geolocator method that is called when this error occurs (including the exact values that are passed in as parameters);
2. The Android device and Android version does this error occur on.

One more thing I would like to check, is it possible you are requesting permissions when the App is running in the background? This is not allowed and is known for throwing a NPE (as Android cannot find an activity to attach the requesting of the permission to).

**Comment by Andrushka1012** [comment]
Hi, it was Samsung Galaxy a51 android 11 device when we calling `Geolocator.getCurrentPosition(desiredAccuracy: LocationAccuracy.high);`. 
I can't reproduce this issue now.
Btw, we are using https://pub.dev/packages/permission_handler plugin for requesting permissions and doing it when app in foreground so maybe it related.

**Comment by kuhnroyal** [comment]
Just got this on `9.0.1` and geolocator_android `4.0.1`.

Non-obfuscated stacktrace:
```
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): Failed to handle method call
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): java.lang.NullPointerException: Attempt to invoke virtual method 'int com.baseflow.geolocator.location.LocationAccuracyStatus.ordinal()' on a null object reference
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at com.baseflow.geolocator.MethodCallHandlerImpl.getLocationAccuracy(MethodCallHandlerImpl.java:162)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at com.baseflow.geolocator.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:71)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at android.os.Handler.handleCallback(Handler.java:938)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at android.os.Looper.loopOnce(Looper.java:226)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at android.os.Looper.loop(Looper.java:313)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/MethodChannel#flutter.baseflow.com/geolocator_android(21045): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

Points to https://github.com/Baseflow/flutter-geolocator/blob/main/geolocator_android/android/src/main/java/com/baseflow/geolocator/MethodCallHandlerImpl.java#L162 - apparently `status`  can be `null` even though there was no error.

**Comment by kuhnroyal** [comment]
Nvm, if there is an error then it is still trying to send the success afterwards.

**Comment by kuhnroyal** [comment]
Created a PR which should fix this.
