### ISSUE TITLE
NPE at com.baseflow.geolocator.StreamHandlerImpl.onListen

### ISSUE THREAD

**Issue by Zverik** [Baseflow/flutter-geolocator#904]
## 🔙 Regression

I get an exception when subscribing to a position event stream.

### Old (and correct) behavior

The code:

```dart
   locSub = Geolocator.getPositionStream(
      locationSettings: LocationSettings(
        accuracy: LocationAccuracy.best,
      ),
    ).listen(
      onLocationEvent,
      onError: onLocationError,
      cancelOnError: true,
    );
```

It worked fine on 7.7.1, with no errors.

### Current behavior

I get this exception:

```
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): Failed to open event stream
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at com.baseflow.geolocator.StreamHandlerImpl.onListen(StreamHandlerImpl.java:89)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onListen(EventChannel.java:188)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at io.flutter.plugin.common.EventChannel$IncomingStreamRequestHandler.onMessage(EventChannel.java:167)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:865)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at android.os.MessageQueue.next(MessageQueue.java:375)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at android.os.Looper.loop(Looper.java:225)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at android.app.ActivityThread.main(ActivityThread.java:6589)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at java.lang.reflect.Method.invoke(Native Method)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
E/EventChannel#flutter.baseflow.com/geolocator_updates( 4116): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

### Configuration

**Version:** 8.0.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @Zverik, 

Thank you very much for reporting this issue. This slipped through the testing cracks unfortunately. I released an hot-fix for the geolocator_android package to solve the problem. You might need to run a `flutter pub upgrade` to make sure you get the latest dependency.

**Comment by Zverik** [comment]
Thank you Mauritz! I'm impressed with your speed :)

Alas the fix introduces another exception:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Long
E/MethodChannel#flutter.baseflow.com/geolocator(18807): 	at com.baseflow.geolocator.location.LocationOptions.parseArguments(LocationOptions.java:16)
```

**Comment by mvanbeusekom** [comment]
Wow that was incredible stupid of me. Sorry about that, introduced another hot-fix which now should work. Appreciate the assistance and reporting of problems.

**Comment by Zverik** [comment]
I guess you need to remove some code from your PR: https://github.com/Baseflow/flutter-geolocator/pull/906/files#diff-d793b0f7157163f750a4174dfcaeecc84bb6b82f5d9c92f1d1c483631b22105d :)

**Comment by mvanbeusekom** [comment]
I am not having a good day today :( sorry about that. Version 3.0.0+4 is released.

**Comment by Zverik** [comment]
Yeah, that's understandable, sorry for reporting these issues so late in a day :)

Just tested both `AndroidSettings()` and `LocationSettings()`, works great now. Thank you!

**Comment by mvanbeusekom** [comment]
Hahaha got another scare when I saw your email notification ;) but luckily this time good news. Thanks again for all your patience.
