### ISSUE TITLE
Leaks on terminated app

### ISSUE THREAD

**Issue by bujdy** [Baseflow/flutter-geolocator#997]
## 💬 Questions and Help

I am opening this issue again because i didnt get any response from previous one.

I wanted to try to listen to locations even after i terminate app so i added 
```foregroundNotificationConfig: const ForegroundNotificationConfig(
            notificationText:
            "Example app will continue to receive your location even when you aren't using it",
            notificationTitle: "Running in Background",
            enableWakeLock: true,
          )
```
to settings. But when i terminate the app i get this leak. If i remove this foregroundNotificationConfig everything works as it should, so if i terminate app there is no leaks.

```
E/ActivityThread(13871): Activity com.enviroapp.enviroapp.MainActivity has leaked ServiceConnection com.baseflow.geolocator.GeolocatorPlugin$1@576aec9 that was originally bound here
E/ActivityThread(13871): android.app.ServiceConnectionLeaked: Activity com.enviroapp.enviroapp.MainActivity has leaked ServiceConnection com.baseflow.geolocator.GeolocatorPlugin$1@576aec9 that was originally bound here
E/ActivityThread(13871): 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1811)
E/ActivityThread(13871): 	at android.app.LoadedApk.getServiceDispatcherCommon(LoadedApk.java:1683)
E/ActivityThread(13871): 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1662)
E/ActivityThread(13871): 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1819)
E/ActivityThread(13871): 	at android.app.ContextImpl.bindService(ContextImpl.java:1749)
E/ActivityThread(13871): 	at android.content.ContextWrapper.bindService(ContextWrapper.java:756)
E/ActivityThread(13871): 	at com.baseflow.geolocator.GeolocatorPlugin.onAttachedToActivity(GeolocatorPlugin.java:126)
E/ActivityThread(13871): 	at io.flutter.embedding.engine.FlutterEngineConnectionRegistry.add(FlutterEngineConnectionRegistry.java:155)
E/ActivityThread(13871): 	at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:29)
E/ActivityThread(13871): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(13871): 	at io.flutter.embedding.engine.plugins.util.GeneratedPluginRegister.registerGeneratedPlugins(GeneratedPluginRegister.java:80)
E/ActivityThread(13871): 	at io.flutter.embedding.android.FlutterActivity.configureFlutterEngine(FlutterActivity.java:1004)
E/ActivityThread(13871): 	at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onAttach(FlutterActivityAndFragmentDelegate.java:191)
E/ActivityThread(13871): 	at io.flutter.embedding.android.FlutterActivity.onCreate(FlutterActivity.java:459)
E/ActivityThread(13871): 	at android.app.Activity.performCreate(Activity.java:8000)
E/ActivityThread(13871): 	at android.app.Activity.performCreate(Activity.java:7984)
E/ActivityThread(13871): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
E/ActivityThread(13871): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
E/ActivityThread(13871): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
E/ActivityThread(13871): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
E/ActivityThread(13871): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/ActivityThread(13871): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/ActivityThread(13871): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
E/ActivityThread(13871): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/ActivityThread(13871): 	at android.os.Looper.loop(Looper.java:223)
E/ActivityThread(13871): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/ActivityThread(13871): 	at java.lang.reflect.Method.invoke(Native Method)
E/ActivityThread(13871): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/ActivityThread(13871): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
D/FlutterGeolocator(13871): Binding to location service.
D/FlutterGeolocator(13871): Destroying location service.
D/FlutterGeolocator(13871): Stop service in foreground.
```

### Expected behavior
Stop listeners on terminated app.
### Reproduction steps
I didnt find anything in issues..
### Configuration
Same as in example 
**Version:** ^8.2.0

**Platform:** 
- [x] :robot: Android

**Comment by mvanbeusekom** [comment]
Hi @bujdy, 

Could you link the original question / issue that you haven't got any response to?

@Wackymax do you mind having a look at this and maybe provide us with some insights? Looks like the android logic forgets to deregister a service connection, however I am not really familiar with this material.

**Comment by mvanbeusekom** [comment]
Looks like we haven't been able to triage it yet. I will close this issue as duplicate, please try not to pollute by creating duplicate issues.
